name: Publish to GitHub Pages

on:
  # Run when `pages` is committed to.
  push:
    branches: [pages]
  # Allow manual invocation.
  workflow_dispatch:

jobs:
  pages:
    # The type of runner that the job will run on.
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Setup Node.js.
      - name: Setup Node.js
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'

      # Checkout `pages`.
      - name: Checkout pages
        uses: actions/checkout@v2
        with:
          ref: pages
          path: pages

      # Checkout `gh-pages`.
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: gh-pages
          path: gh-pages

      # Build & export Next.js static website.
      - name: Build & export
        run: |
          cd pages

          npm install
          npm run build
          npm run export

          git rev-parse HEAD > ../hash

      # Commit to gh-pages.
      - name: Commit gh-pages
        run: |
          cd gh-pages
          rm -rf *
          mv ../pages/out/** .
          touch .nojekyll
          echo 'doubtfire.io' >CNAME

          git add .
          git config --local user.email "actions@users.noreply.github.com"
          git config --local user.name "GitHub Actions"
          git commit -m "Publish $(cat ../hash)"

      # Push
      - name: Push gh-pages
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          directory: gh-pages
